server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5001/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limits:
        max_items: 150
    # templates: /path/to/templates
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net
    manager:
        name: TinyDB
        connection: /tmp/pygeoapi-process-manager.db
        output_dir: /tmp/

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Diving into pygeoapi default instance
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://dive.pygeoapi.io
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi Development Team
        url: https://pygeoapi.io
    contact:
        name: pygeoapi Development Team
        position: pygeoapi Development Team
        address: 9450 SW Gemini Dr. #42523
        city: Beaverton
        stateorprovince: Oregon
        postalcode: 97008
        country: United States of America
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: pygeoapi@gmail.com
        url: https://pygeoapi.io
        hours: 24/7
        instructions: During hours of service.
        role: pointOfContact

resources:
    canada-hydat-daily-mean-02hc003:
        type: collection
        title: Daily Mean of Water Level or Flow
        description: The daily mean is the average of all unit values for a given day.
        keywords: [Daily, Daily Mean, Water Level, Flow, Discharge]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
              hreflang: en-CA
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              rel: download
              title: download data
              href: https://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1850-01-01T00:00:00Z
                end: null # or empty

        providers:
            - type: feature
              name: TinyDB
              data: /pygeoapi/tests/data/canada-hydat-daily-mean-02HC003.tinydb
              id_field: IDENTIFIER
              time_field: DATE
              crs:
                - http://www.opengis.net/def/crs/OGC/1.3/CRS84
                - http://www.opengis.net/def/crs/EPSG/0/4326
                - http://www.opengis.net/def/crs/EPSG/0/3348
              storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
