name: Test your OGC API ⚙️

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pygeoapi:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set environment variable for port
      run: cat ./apps/pygeoapi/.env >> $GITHUB_ENV

    - name: Check port
      run: echo $PORT

    - name: Start containers
      run: docker compose -f "./apps/pygeoapi/docker-compose.yml" up -d --build
          
    - name: Test OGC API - Features compliance
      uses: OSGeo/ogc-cite-runner@v0.3.0
      with:
        test_suite_identifier: ogcapi-features-1.0
        test_session_arguments: iut=http://host.docker.internal:$PORT
        with_failed: true

    - name: Stop containers
      if: always()
      run: docker compose -f "./apps/pygeoapi/docker-compose.yml" down -v
