name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pygeoapi:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Read Port
      run: cat ./apps/pygeoapi/.env >> $GITHUB_ENV

    - name: Check Port
      run: echo $PORT

    - name: Start containers
      run: docker compose -f "./apps/pygeoapi/docker-compose.yml" up -d --build
          
    - name: test ogcapi-features compliance
      uses: OSGeo/cite-runner@main # TODO: change this later to match the latest release
      with:
        test_suite_identifier: ogcapi-features-1.0
        test_session_arguments: iut=http://localhost:$PORT

    - name: Stop containers
      if: always()
      run: docker compose -f "./apps/pygeoapi/docker-compose.yml" down -v